name: mdairtrip
description: Small demo/tutorial project for mdcdavan.
# version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  mdcdavan:
    git: https://github.com/jonboj/mdcdavan.git

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
